src/GG.Portafolio.Site/Controllers/BlogController.cs
using GG.Portafolio.Shared;
using GG.Portafolio.Shared.Blog;
using GG.Portafolio.Site.Generic.Interfaces;
using IdentityModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Linq;
using System.Net;
using System.Reflection;
using System.Security.Claims;
using System.Threading.Tasks;

namespace GG.Portafolio.Site.Controllers
{
    public class BlogController : Controller
    {
        private readonly ILogger<BlogController> _logger;        
        private readonly IHttpClient _httpClient;

        public BlogController(ILogger<BlogController> logger, IHttpClient httpClient)
        { 
            _logger = logger;
            _httpClient = httpClient;            
        }

        [Route("blog/{title}")]
        public async Task<IActionResult> Index(string title)
        {
            BlogContentWithCommentsReponse model = null;

            try
            {
                (BlogContentWithCommentsReponse Ok, _, HttpStatusCode Status)  =
                    await _httpClient.GetAsync<BlogContentWithCommentsReponse, ErrorApi>($"Blog/getbytitle/{title}", _logger);

                if (Status == HttpStatusCode.OK)
                {
                    model = Ok;
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "{Name}", MethodBase.GetCurrentMethod().Name);
            }

            return View(model ?? new BlogContentWithCommentsReponse());
        }


        [Route("savecomment")]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<JsonResult> SaveComment(BlogComments comments)
        {
            bool result = false;

            try
            {
                if (ModelState.IsValid)
                {
                    string userId = HttpContext.User?.Claims?.FirstOrDefault(x => x.Type == JwtClaimTypes.Subject || x.Type == ClaimTypes.NameIdentifier)?.Value;
                    comments.Date = DateTime.Now;
                    comments.User_Id = userId;
                    (_, _, HttpStatusCode StatusCode) = await _httpClient.PostAsync<string, ErrorApi>("Blog/commentsave", comments, _logger);
                    result = StatusCode == HttpStatusCode.OK;
                }
            }
            catch (Exception ex)
            {
                _logger?.LogError(ex, "{Name}  BlogId:{BlogId} Date:{Date} Name:{Name} Content:{Content}",
                   MethodBase.GetCurrentMethod().Name, comments.BlogId, comments.Date, comments.Name, comments.Content);
            }

            return Json(new
            {
                success = result,
                comments.Name,
                Comment = comments.Content,
                Date = comments.Date.ToString("dd/MM/yyyy HH:mm:ss")
            });
        }
    }
}

src/GG.Portafolio.Site/Controllers/BlogManagementController.cs
using GG.Portafolio.Shared;
using GG.Portafolio.Shared.Blog;
using GG.Portafolio.Site.Generic.Interfaces;
using GG.Portafolio.Site.Models;
using IdentityModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Reflection;
using System.Security.Claims;
using System.Threading.Tasks;

namespace GG.Portafolio.Site.Controllers
{
    [Authorize(Policy.PolicyBasic)]
    [Authorize(Policy.PolicyAdmin)]
    public class BlogManagementController : Controller
    {
        private const string _nameFileImage = "imgtmp";

        private readonly ILogger<BlogManagementController> _logger;
        private readonly IHttpClientWithToken _httpClient;
        private readonly ConfigurationValues _configurationValues;
        private readonly IWebHostEnvironment _environment;

        public BlogManagementController(ILogger<BlogManagementController> logger, IHttpClientWithToken httpClient, IOptions<ConfigurationValues> options,
            IWebHostEnvironment environment)
        { 
            _logger = logger;
            _httpClient = httpClient;
            _configurationValues = options.Value;
            _environment = environment;
        }

        private async Task<T> GetBlogManagementById<T>(string blog, bool raiseException = true)
        {
            (T Ok, _, HttpStatusCode CodeStatus) =
                await _httpClient.GetAsync<T, ErrorApi>($"Blog/get/{blog}", HttpContext, _logger);

            if (CodeStatus == HttpStatusCode.OK)
            {
                return Ok;
            }
            else if (raiseException)
            {
                throw new Exception($"No se pudo recuperar el blog {blog}");
            }
            else
            {
                return default;
            }
        }

        public async Task<IActionResult> Index()
        {
            List<BlogResponse> blogs = new();

            try
            {
                (IEnumerable<BlogResponse> Ok, ErrorApi ErrorApi, HttpStatusCode Status) = 
                    await _httpClient.GetAsync<IEnumerable<BlogResponse>, ErrorApi>("Blog/get", HttpContext, _logger);

                if (Status == HttpStatusCode.OK)
                { 
                    blogs.AddRange(Ok);
                }

                if (TempData["DeleteBlogBackup"] != null)
                {
                    ViewBag.DeleteBlogBackup = true;
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "{Name}", MethodBase.GetCurrentMethod().Name);
            }

            return View(blogs);
        }

        public async Task<IActionResult> NewEdit(string blog)
        {
            BlogManagementModel model = null;            
            try
            {
                ViewData["Operation"] = string.IsNullOrWhiteSpace(blog) ? "Nuevo": "Editar";
                ViewData["TinymceKey"] = _configurationValues.TinymceKey;

                model = string.IsNullOrWhiteSpace(blog) ? new BlogManagementModel { CreateDate = DateTime.Now.Ticks } :
                    await GetBlogManagementById<BlogManagementModel>(blog);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "{Name} {blog}", MethodBase.GetCurrentMethod().Name, blog);
                ViewBag.ListError = new List<string> { "No se pudo recuperar el blog." };
            }

            return View("~/Views/BlogManagement/NewEdit.cshtml", model ?? new BlogManagementModel());
        }

        [HttpPost]
        public JsonResult SaveImage(ImgageLoad model)
        {
            ImageLoadResponse response = new() { Success = false };
            try
            {
                if (ModelState.IsValid)
                {
                    string subject = HttpContext.User.Claims.FirstOrDefault(x => x.Type == JwtClaimTypes.Subject || x.Type == ClaimTypes.NameIdentifier)?.Value;
                    string pathDirectory = Path.Combine(_environment.WebRootPath, _nameFileImage, subject);
                    string fileName = $"{DateTime.Now.Ticks}{Path.GetExtension(model.FileName)}";
                    string pathFile = Path.Combine(pathDirectory, fileName);

                    if (!Directory.Exists(pathDirectory))
                    {
                        Directory.CreateDirectory(pathDirectory);
                    }

                    if (!System.IO.File.Exists(pathFile))
                    {
                        System.IO.File.WriteAllBytes(pathFile, model.FileContent);
                    }

                    response.Success = true;
                    response.FileName = fileName;
                    response.Url = $"/{_nameFileImage}/{subject}/{fileName}";
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "{Name}", MethodBase.GetCurrentMethod().Name);
            }

            return Json(response);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Save(BlogManagementModel model)
        {
            try
            {
                ViewData["Operation"] = string.IsNullOrWhiteSpace(model.Id) ? "Nuevo" : "Editar";
                ViewData["TinymceKey"] = _configurationValues.TinymceKey;

                if (ModelState.IsValid)
                {
                    string userId = HttpContext.User.Claims.FirstOrDefault(x => x.Type == JwtClaimTypes.Subject || x.Type == ClaimTypes.NameIdentifier)?.Value;
                    string pathfiles = Path.Combine(_environment.WebRootPath, _nameFileImage, userId);
                    BlogContentReponse Ok= await GetBlogManagementById<BlogContentReponse>(string.IsNullOrWhiteSpace(model.Id) ? "0" : model.Id,false);

                    BlogNewRequest newRequest = Ok == null ?
                        new BlogNewRequest()
                        {
                            Title = model.Title,
                            Content = model.Content,
                            Dsc = model.Dsc,
                            UserId = userId,
                        } :
                        new BlogEditRequest()
                        {
                            Title = model.Title,
                            Content = model.Content,
                            Dsc = model.Dsc,
                            UserId = userId,
                            Id = model.Id,
                        };

                    List<string> files = model.Images?.Split(new char[] { '|' }, StringSplitOptions.RemoveEmptyEntries).ToList();

                    files?.ForEach(x =>
                    {
                        string[] fileStruct = x.Split(new char[] { '/' }, StringSplitOptions.RemoveEmptyEntries);

                        string filePath = Path.Combine(pathfiles, fileStruct[^1]);

                        newRequest.ContentFiles.Add(new ContentFile
                        {
                            File = System.IO.File.ReadAllBytes(filePath),
                            Name = fileStruct[^1],
                            Url = x
                        });
                    });

                    (BlogOperationResponse Response, ErrorApi Error1, HttpStatusCode Status1) = Ok == null ?
                        await _httpClient.PostAsync<BlogOperationResponse, ErrorApi>("Blog/create", newRequest, HttpContext, _logger) :
                        await _httpClient.PutAsync<BlogOperationResponse, ErrorApi>("Blog/modify", newRequest, HttpContext, _logger);

                    if (Status1 == HttpStatusCode.OK)
                    {
                        if (Directory.Exists(pathfiles))
                        {
                            Directory.Delete(pathfiles, true);
                        }
                        TempData["DeleteBlogBackup"] = true;
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ViewBag.ListError = Response.Errores;
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "{Name}", MethodBase.GetCurrentMethod().Name);
                ViewBag.ListError = new List<string> { "Error al guardar el blog." };
            }

            return View("~/Views/BlogManagement/NewEdit.cshtml", model);
        }

        public async Task<IActionResult> Delete(string blog)
        {
            try
            {
                _ = await _httpClient.DeleteAsync<string,ErrorApi>($"Blog/delete/{blog}", HttpContext, _logger);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "{Name}", MethodBase.GetCurrentMethod().Name);
            }

            return RedirectToAction("Index");
        }
    }
}

src/GG.Portafolio.Site/Views/BlogManagement/Index.cshtml
@using GG.Portafolio.Shared.Blog
@model List<BlogResponse>;

@{
    ViewData["Title"] = "Blog Management";
}

@section Style{
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.css" />
    </environment>

    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" />
    </environment>
}

<div class="row">
    <div class="col text-center header">
        Administración del <span class="color-text-red">- Blog</span>
    </div>
</div>

<div class="row">
    <div class="col text-center header-caption">
        <span class="header-caption">Blo <span class="color-text-red">gs.</span></span>
    </div>
</div>

<br />
<br />

<div class="row">
    <div class="col-md-5 offset-md-1 align-content-end text-end">
        <a href="@Url.Action("NewEdit","BlogManagement", new { blog = string.Empty })" class="btn btn-primary" >
            <i class="bi bi-plus"></i>
        </a>
    </div>
</div>
<br />

<div class="row blog-management">
    <div class="col-md-2 offset-md-1 blog-description">
        
    </div>
    <div class="col-md-2 blog-description">
        <span class="align-middle">
           Titulo
        </span>
    </div>
    <div class="col-md-2 blog-description">
        <span class="align-middle">
            Descripción
        </span>
    </div>
    <div class="col-md-2 blog-description">
        <span class="align-middle">
            Url
        </span>
    </div>
</div>

@foreach(var item in Model)
{
    <br />
    <div class="row blog-management">
        <div class="col-md-2 offset-md-1 blog-description">
            <a href="@Url.Action("NewEdit", "BlogManagement", new { blog = item.Id })" class="link-primary">Editar</a>
            <a href="@Url.Action("Delete", "BlogManagement", new { blog = item.Id })" class="link-primary">Eliminar</a>
        </div>
        <div class="col-md-2 blog-description">
            <span class="align-middle">
               @item.Title
            </span>
        </div>
        <div class="col-md-2 blog-description">
            <span class="align-middle">
                @item.Dsc
            </span>
        </div>
        <div class="col-md-2 blog-description">
            <span class="align-middle">
                <a href="@Url.Action("Index", "Blog", new { @item.Title })">
                    @Html.Raw(Url.Action("Index", "Blog", new { @item.Title }))
                </a>
            </span>
        </div>
    </div>
}

@if (ViewBag.DeleteBlogBackup != null && ViewBag.DeleteBlogBackup)
{
    @section Scripts{
        <script type="text/javascript">
            localStorage.removeItem("blog");
        </script>
    }
}

src/GG.Portafolio.Site/Views/BlogManagement/NewEdit.cshtml
@model BlogManagementModel

@{
    ViewData["Title"] = $"Management Blog {ViewData["Operation"]}";
    IEnumerable<string> Errores = ViewBag.ListError ?? new List<string>();
}

<div class="row">
    <div class="col text-center header">
        Administración del <span class="color-text-red">- Blog</span>
    </div>
</div>

<div class="row">
    <div class="col text-center header-caption">
        <span class="header-caption">Operación <span class="color-text-red">@ViewData["Operation"]</span></span>
    </div>
</div>

<br />
<br />

<form asp-action="Save" asp-controller="BlogManagement" asp-antiforgery="true" method="post" class="needs-validation" novalidate>
    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="CreateDate" />
    <input type="hidden" asp-for="Images" />

    @foreach (var item in Errores)
    {
        <div class="row">
            <div class="col-md-5 offset-md-1 text-start">
                <label class="col-form-label">@Html.Raw(item)</label>
            </div>
        </div>
    }

    <div class="row g-5">
        <div class="col-md-5 offset-md-1 text-end">
            <label asp-for="CreateDate" class="col-form-label"></label>
        </div>
        <div class="col-md-5">
            <label class="col-form-label" >@(new DateTime(Model.CreateDate).ToString("dd/MM/yyyyy"))</label>
        </div>
    </div>
    <br />

    <div class="row g-5">
         <div class="col-md-5 offset-md-1 text-end">
            <label asp-for="Title" class="col-form-label"></label>
         </div>
         <div class="col-md-5">
            <input asp-for="Title" class="form-control" required>
         </div>
    </div>
    <br />

    <div class="row g-5">
        <div class="col-md-5 offset-md-1 text-end">
            <label class="col-form-label">URL</label>
        </div>
        <div class="col-md-5">
            <label class="col-form-label" id="UrlText">@(Url.Action("index","Blog", new {desc = Model.Title }))</label>
        </div>
    </div>
    <br />
    
    <div class="row g-5">
         <div class="col-md-5 offset-md-1 text-end">
            <label asp-for="Dsc" class="col-form-label"></label>
         </div>
         <div class="col-md-5">
            <input asp-for="Dsc" class="form-control" required>
         </div>
    </div>
    <br />

     <div class="row g-5">         
         <div class="col-md-10 offset-1">
            <textarea asp-for="Content" required class="form-control"></textarea>
         </div>
    </div>
    <br />

     <div class="row">
        <div class="col text-center">
            <button type="submit" id="submit" value="send" class="btn btn-primary btn-lg" >Enviar</button>
        </div>
    </div>
</form>

<br />

@section Scripts{
    <script src="https://cdn.tiny.cloud/1/@ViewData["TinymceKey"]/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>

    <script src="~/js/neweditblog.js" asp-append-version="true"></script>

    <script type="text/javascript">

        var idTextArea = '#@Html.IdFor(x => x.Content)',
            idTitle ='@Html.IdFor(x => x.Title)',
            idurlText = 'UrlText',
            blogUrl = '@Url.Action("index", "Blog")',
            LoadImageUrl = '@Url.Action("SaveImage", "BlogManagement")',
            idImages = '@Html.IdFor(x => x.Images)',
            idBlog = '@Html.IdFor(x => x.Id)',
            idCreateDate ='@Html.IdFor(x => x.CreateDate)',
            idDsc = '@Html.IdFor(x => x.Dsc)',
            idContent = '@Html.IdFor(x => x.Content)';

        window.onload = function load() {        
            neweditblog(idurlText,idTitle,blogUrl,idBlog,idCreateDate,idImages,idDsc,idContent);

            tinymce.init({
                selector: idTextArea,
                plugins: 'image code',
                height:600,
                images_upload_handler: function (blobInfo, success, failure) {
                    var formData = new FormData();

                    formData.append('FileContent', blobInfo.base64());
                    formData.append('FileName', blobInfo.filename());
                    formData.append('Id', document.getElementById('@Html.IdFor(x => x.Id)').value);

                    fetch(LoadImageUrl, {
                      method: 'POST',
                      body: formData,
                      credentials: 'same-origin'
                    })
                    .then(response => response.json())
                    .then(response => {                        
                        if(response.success) {
                         success(response.url);
                         document.getElementById(idImages).value += response.url + '|';
                         changedImages(document.getElementById(idImages).value);
                        }
                        else {
                            failure("Ocurrio un error");
                        }
                    })
                    .catch(error => failure(error));
                },
                init_instance_callback: function (editor) {
                    editor.on('input', function (e) {
                        changedContent(e.target.innerHTML);
                    });
                }
            }); 
        };
    </script>
}