src/GG.Portafolio.Site/Controllers/BlogController.cs
using GG.Portafolio.Shared;
using GG.Portafolio.Shared.Blog;
using GG.Portafolio.Site.Generic.Interfaces;
using IdentityModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Linq;
using System.Net;
using System.Reflection;
using System.Security.Claims;
using System.Threading.Tasks;

namespace GG.Portafolio.Site.Controllers
{
    public class BlogController : Controller
    {
        private readonly ILogger<BlogController> _logger;        
        private readonly IHttpClient _httpClient;

        public BlogController(ILogger<BlogController> logger, IHttpClient httpClient)
        { 
            _logger = logger;
            _httpClient = httpClient;            
        }

        [Route("blog/{title}")]
        public async Task<IActionResult> Index(string title)
        {
            BlogContentWithCommentsReponse model = null;

            try
            {
                (BlogContentWithCommentsReponse Ok, _, HttpStatusCode Status)  =
                    await _httpClient.GetAsync<BlogContentWithCommentsReponse, ErrorApi>($"Blog/getbytitle/{title}", _logger);

                if (Status == HttpStatusCode.OK)
                {
                    model = Ok;
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "{Name}", MethodBase.GetCurrentMethod().Name);
            }

            return View(model ?? new BlogContentWithCommentsReponse());
        }


        [Route("savecomment")]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<JsonResult> SaveComment(BlogComments comments)
        {
            bool result = false;

            try
            {
                if (ModelState.IsValid)
                {
                    string userId = HttpContext.User?.Claims?.FirstOrDefault(x => x.Type == JwtClaimTypes.Subject || x.Type == ClaimTypes.NameIdentifier)?.Value;
                    comments.Date = DateTime.Now;
                    comments.User_Id = userId;
                    (_, _, HttpStatusCode StatusCode) = await _httpClient.PostAsync<string, ErrorApi>("Blog/commentsave", comments, _logger);
                    result = StatusCode == HttpStatusCode.OK;
                }
            }
            catch (Exception ex)
            {
                _logger?.LogError(ex, "{Name}  BlogId:{BlogId} Date:{Date} Name:{Name} Content:{Content}",
                   MethodBase.GetCurrentMethod().Name, comments.BlogId, comments.Date, comments.Name, comments.Content);
            }

            return Json(new
            {
                success = result,
                comments.Name,
                Comment = comments.Content,
                Date = comments.Date.ToString("dd/MM/yyyy HH:mm:ss")
            });
        }
    }
}

src/GG.Portafolio.Site/Controllers/DealerController.cs
using GG.Portafolio.Shared;
using GG.Portafolio.Shared.Dealer;
using GG.Portafolio.Site.Generic.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Net;
using System.Reflection;
using System.Threading.Tasks;
using System.Web;

namespace GG.Portafolio.Site.Controllers
{
    public class DealerController : Controller
    {
        private readonly ILogger<DealerController> _logger;

        private readonly IHttpClient _httpClient;

        public DealerController(ILogger<DealerController> logger, IHttpClient httpClient)
        {
            _logger = logger;
            _httpClient = httpClient;

        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<JsonResult> GetData([FromQuery]DateTime date)
        {
            try
            {
                var dateparse = HttpUtility.ParseQueryString(date.ToString("MM/dd/yyyy HH:mm:ss"));                
                var timeHttp = _httpClient.GetAsync<TimeList, ErrorApi>($"Dealer/gettimelist?date={dateparse}", _logger);
                var dealerHttp = _httpClient.GetAsync<List<DeliveryMan>, ErrorApi>("Dealer/deliveryman", _logger);

                (TimeList Ok, ErrorApi Error, HttpStatusCode StatusCode) timeList =  await timeHttp;
                (List<DeliveryMan> Ok, ErrorApi Error, HttpStatusCode StatusCode) deliveryMans = await dealerHttp;

                if (timeList.StatusCode == HttpStatusCode.OK && deliveryMans.StatusCode == HttpStatusCode.OK)
                {
                    return Json(new { Success = true, deliveries = deliveryMans.Ok, dates = timeList.Ok });
                }
                else
                {
                    return Json(new { Success = false });
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "{Name} {date}", MethodBase.GetCurrentMethod().Name, date);
                return Json(new { Success = false });
            }
        }
    }
}

src/GG.Portafolio.Site/Controllers/HomeController.cs
using GG.Portafolio.Shared.Blog;
using GG.Portafolio.Site.Generic.Interfaces;
using GG.Portafolio.Site.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Reflection;
using System.Threading.Tasks;
using GG.Portafolio.Shared;

namespace GG.Portafolio.Site.Controllers
{
    [AllowAnonymous]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IHttpClient _httpClient;

        public HomeController(ILogger<HomeController> logger, IHttpClient httpClient)
        {
            _logger = logger;
            _httpClient = httpClient;
        }

        private async Task<List<List<BlogResponse>>> GetBlogs()
        {
            List<List<BlogResponse>> blogs = new();

            try
            {
                (IEnumerable<BlogResponse> Ok, ErrorApi ErrorApi, HttpStatusCode Status) =
                 await _httpClient.GetAsync<IEnumerable<BlogResponse>, ErrorApi>("Blog/get", _logger);

                if (Status == HttpStatusCode.OK)
                {
                    blogs.AddRange(Ok.OrderByDescending(x => x.CreateDate).Select((x, i) => new { Index = i, Value = x })
                      .GroupBy(x => x.Index / 2)
                      .Select(x => x.Select(v => v.Value).ToList()).ToList());
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "{Name}", MethodBase.GetCurrentMethod().Name);
            }

            return blogs;
        }

        public async Task<IActionResult> Index()
        {
            DefaultViews defaultViews = TempData.ContainsKey("DefaultViews") ? (DefaultViews)TempData["DefaultViews"] : DefaultViews.Home;
            if (defaultViews == DefaultViews.Blog)
            { 
                ViewBag.Blogs = await GetBlogs();
            }
            ViewBag.Home = true;

            return View(defaultViews);
        }

        public IActionResult RedirectMenu(string url)
        {
            DefaultViews defaultViews = url switch
            {
                "blog" => DefaultViews.Blog,
                "aboutme" => DefaultViews.AboutMe,
                "portfolio" => DefaultViews.Portfolio,
                _ => DefaultViews.Home,
            };

            TempData["DefaultViews"] = defaultViews;

            return RedirectToAction("Index");
        }

        public PartialViewResult Home()
        {
            return PartialView();
        }

        public PartialViewResult AboutMe() 
        {
            return PartialView();
        }

        public PartialViewResult Portfolio()
        {
            return PartialView();
        }

        public async Task<PartialViewResult> Blogs()
        {
            return PartialView(await GetBlogs());
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/GG.Portafolio.Site/Controllers/TemplateWordController.cs
using GG.Portafolio.Shared;
using GG.Portafolio.Shared.TemplateWord;
using GG.Portafolio.Site.Generic.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Net;
using System.Reflection;
using System.Threading.Tasks;

namespace GG.Portafolio.Site.Controllers
{
    public class TemplateWordController : Controller
    {
        private readonly ILogger<TemplateWordController> _logger;

        private readonly IHttpClient _httpClient;

        public TemplateWordController(ILogger<TemplateWordController> logger, IHttpClient httpClient)
        { 
            _logger = logger;
            _httpClient = httpClient;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(new TemplateRequest());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(TemplateRequest model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    (TemplateResponse Ok, ErrorApi Error, HttpStatusCode StatusCode) response =
                        await _httpClient.PostAsync< TemplateResponse, ErrorApi> ("TemplateWord/generatetemplate", model, _logger);

                    if (response.StatusCode == HttpStatusCode.OK) 
                    {
                        return File(response.Ok.File, "application/vnd.openxmlformats-officedocument.wordprocessingml.document", $"{model.Name}.{response.Ok.Extension}");
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "{Name} {model}", MethodBase.GetCurrentMethod().Name, model);
            }

            return View(model);
        }

        [HttpGet]        
        public async Task<IActionResult> GetTemplate()
        {
            try
            {
                (TemplateResponse Ok, ErrorApi Error, HttpStatusCode StatusCode) model = await _httpClient.GetAsync<TemplateResponse, ErrorApi>("TemplateWord/downloadtemplate", _logger);

                if (model.StatusCode == HttpStatusCode.OK)
                {
                    return File(model.Ok.File, "application/vnd.openxmlformats-officedocument.wordprocessingml.document", $"template.{model.Ok.Extension}");
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "{Name}", MethodBase.GetCurrentMethod().Name);
            }

            return Problem("Error",statusCode: (int)HttpStatusCode.NotFound);
        }
    }
}

src/GG.Portafolio.Site/Views/Home/AboutMe.cshtml
<script type="text/javascript" id="scriptViewAboutMe">    
    loadedPartView();
    function loadedPartView() {
        var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'));
        var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
            return new bootstrap.Tooltip(tooltipTriggerEl);
        });

        var links = document.querySelectorAll('[class="list-group-item list-group-item-action list-group-item-dark"]');

        for (var i = 0; i < links.length; i++) {
            links[i].addEventListener("click", function (e) {
                e.preventDefault();
                return false;
            });
        }
    }
</script>

<div class="row">
    <div class="col text-center header">
        Sobre <span class="color-text-red">Mí</span>
    </div>
</div>

<div class="row">
    <div class="col text-center header-caption">
        <span class="header-caption">Conoce un poco de <span class="color-text-red">mí.</span></span>
    </div>
</div>

<div class="row g-0 about">
    <div class="col-md-5 offset-md-1 about-orden-1">
        <span class="first-line">
            Soy un
            <span class="color-text-red">desarrollador de software</span>
            con residencia en Querétaro, México
        </span>
        <br /><br />
        <span class="second-line">
            Cuento con más de 10 años de experiencia como desarrollador de software profesional, durante este tiempo he adquirido las habilidades y conocimientos necesarios para que su proyecto sea exitoso.
            <br />            
            <br /> 
            Contáctame y platiquemos sobre tu proyecto, veamos la forma de poder colaborar juntos.
        </span>
    </div>
    <div class="col-md-5 about-img about-orden-2">
        <img src="~/images/IMG_2325_1.jpg" alt="my image">
    </div>
</div>

<br />
<br />

<div class="row">
    <div class="col text-center header">
        Mis <span class="color-text-red">conocimientos</span>
    </div>
</div>

<br />
<br />

<div class="row g-4 about">

    <div class="col-md-3 offset-md-1 service">
        <div class="service-img">
            <img src="~/images/coding.png" alt="service-one">
        </div>
        <div class="service-description">
            <h2>Frontend</h2>
            <p>Creación y mantenimiento de páginas, sitios y aplicaciones web.</p>
        </div>
    </div>

    <div class="col-md-3 service">
        <div class="service-img">
            <img src="~/images/backend.png" alt="service-two">
        </div>
        <div class="service-description">
            <h2>Backend</h2>
            <p>Creación y mantenimiento de web api (restful), web services y WCF (Windows Communication Foundation)</p>
        </div>
    </div>

    <div class="col-md-3 service">
        <div class="service-img">
            <img src="~/images/desktop.png" alt="service-three">
        </div>
        <div class="service-description">
            <h2>Desktop</h2>
            <p>Creación y mantenimiento de aplicaciones de escritorio, especializado en tecnologías Microsoft (window form, wpf, windws services y consola).</p>
        </div>
    </div>
</div>

<br />
<br />

<div class="row">
    <div class="col text-center header">
        Mis <span class="color-text-red">Habilidades</span>
    </div>
</div>

<br />
<br />

<div class="row g-0 about" onload="loaded" id="divPruebas">

    <div class="col-md-4 offset-md-4">
        <div class="list-group list-group-horizontal-sm">
            <a href="#" class="list-group-item list-group-item-action list-group-item-dark"
               data-bs-toggle="tooltip" data-bs-placement="top" title="C#">
                <img src="~/images/languages/csharp.png" class="rounded img-thumbnail" alt="C#" />
            </a>
            <a href="#" class="list-group-item list-group-item-action list-group-item-dark"
               data-bs-toggle="tooltip" data-bs-placement="top" title="SQL Server">
                <img src="~/images/languages/sql server.png" class="rounded img-thumbnail" alt="SQL Server" />
            </a>
            <a href="#" class="list-group-item list-group-item-action list-group-item-dark"
               data-bs-toggle="tooltip" data-bs-placement="top" title="Visual Studio">
                <img src="~/images/languages/vs.png" class="rounded img-thumbnail" alt="Visual Studio"/>
            </a>
        </div>

        <div class="list-group list-group-horizontal-sm">
            <a href="#" class="list-group-item list-group-item-action list-group-item-dark"
               data-bs-toggle="tooltip" data-bs-placement="top" title="HTML">
                <img src="~/images/languages/html.png" class="rounded img-thumbnail" alt="HTML"/>
            </a>
            <a href="#" class="list-group-item list-group-item-action list-group-item-dark"
               data-bs-toggle="tooltip" data-bs-placement="top" title="JavaScript">
                <img src="~/images/languages/js.png" class="rounded img-thumbnail" alt="Javascript" />
            </a>
            <a href="#" class="list-group-item list-group-item-action list-group-item-dark"
               data-bs-toggle="tooltip" data-bs-placement="top" title="HTML">
                <img src="~/images/languages/css.png" class="rounded img-thumbnail" alt="CSS"/>
            </a>
        </div>

        <div class="list-group list-group-horizontal-sm">
            <a href="#" class="list-group-item list-group-item-action list-group-item-dark"
               data-bs-toggle="tooltip" data-bs-placement="top" title="MySql">
                <img src="~/images/languages/mysql.png" class="rounded img-thumbnail" alt="MySql"/>
            </a>
            <a href="#" class="list-group-item list-group-item-action list-group-item-dark"
               data-bs-toggle="tooltip" data-bs-placement="top" title="SQLite">
                <img src="~/images/languages/sqlite.png" class="rounded img-thumbnail" alt="Sqlite"/>
            </a>
            <a href="#" class="list-group-item list-group-item-action list-group-item-dark"
               data-bs-toggle="tooltip" data-bs-placement="top" title="Java">
                <img src="~/images/languages/Java.png" class="rounded img-thumbnail" alt="Java"/>
            </a>
        </div>

        <div class="list-group list-group-horizontal-sm">
            <a href="#" class="list-group-item list-group-item-action list-group-item-dark"
               data-bs-toggle="tooltip" data-bs-placement="top" title="Bootstrap">
                <img src="~/images/languages/bootstrap.png" class="rounded img-thumbnail" alt="Bootstrap"/>
            </a>
            <a href="#" class="list-group-item list-group-item-action list-group-item-dark"
               data-bs-toggle="tooltip" data-bs-placement="top" title="JQuery">
                <img src="~/images/languages/jquery.png" class="rounded img-thumbnail" alt="JQuery"/>
            </a>
            <a href="#" class="list-group-item list-group-item-action list-group-item-dark"
               data-bs-toggle="tooltip" data-bs-placement="top" title="Sass">
                <img src="~/images/languages/sass.png" class="rounded img-thumbnail" alt="Sass"/>
            </a>
        </div>

        <div class="list-group list-group-horizontal-sm">
            <a href="#" class="list-group-item list-group-item-action list-group-item-dark"
               data-bs-toggle="tooltip" data-bs-placement="top" title="TypeScript">
                <img src="~/images/languages/typescript.svg" class="rounded img-thumbnail" alt="TypeScript"/>
            </a>
            <a href="#" class="list-group-item list-group-item-action list-group-item-dark"
               data-bs-toggle="tooltip" data-bs-placement="top" title="Xamarin">
                <img src="~/images/languages/xamarin.png" class="rounded img-thumbnail" alt="Xamarin"/>
            </a>
            <a href="#" class="list-group-item list-group-item-action list-group-item-dark">
                
            </a>
        </div>

    </div>

</div>

src/GG.Portafolio.Site/Views/Home/Blogs.cshtml
@using GG.Portafolio.Shared.Blog
@model List<List<BlogResponse>>;


<div class="row">
    <div class="col text-center header">
         Blogs
    </div>
</div>

<div class="row">
    <div class="col text-center header-caption">
        <span class="header-caption">Mis últimas publicaciones de<span class="color-text-red"> blog.</span></span>
    </div>
</div>

<br />

@foreach(var item in Model)
{
    <div class="row g-0 about">
        
        <div class="col-md-5 offset-md-1 image">
            <div class="blogs">
                <a href="@(Url.Action("index","Blog", new {title = item[0].Title }))">
                    <div class="img">
                        <img src="~/images/post-one.jpg" alt="pruebas">
                        <div class="blog-date">@(new DateTime(item[0].CreateDate).ToString("dd/MM/yyyy"))</div>
                    </div>
                    <div class="blog-text">
                        <h3>@item[0].Title</h3>
                        <p>
                            @item[0].Dsc
                        </p>
                    </div>
                </a>
            </div>
        </div>

        @if (item.Count() == 2)
        {
            <div class="col-md-5 align-self-center">
                 <div class="blogs">
                    <a href="@(Url.Action("index","Blog", new {title = item[1].Title }))">
                        <div class="img">
                            <img src="~/images/portfolio-second.jpg" alt="pruebas">
                            <div class="blog-date">@(new DateTime(item[1].CreateDate).ToString("dd/MM/yyyy"))</div>
                        </div>
                        <div class="blog-text">
                            <h3>@item[1].Title</h3>
                            <p>
                                @item[1].Dsc
                            </p>
                        </div>
                    </a>
                </div>
            </div>
        }
    </div>
}

src/GG.Portafolio.Site/Views/Home/Home.cshtml
<div class="row g-0">
    <div class="col-md-1 home-order-1">
        <div class="social-media-links">
            <a href="https://github.com/guillermo-galvan" target="_blank">
                <svg height="32" aria-hidden="true" viewBox="0 0 16 16" version="1.1" width="32" data-view-component="true" 
                     class="octicon octicon-mark-github v-align-middle social-media" 
                     style="fill: currentColor; color: white;">
                     <title>Github</title>
                    <path fill-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z"></path>
                </svg>
            </a>
            <a href="https://www.facebook.com/profile.php?id=100078937306888" target="_blank">
                <svg viewBox="0 0 36 36" class="a8c37x1j ms05siws hwsy1cff b7h9ocf4 social-media" fill="url(#jsc_c_2)" height="40" width="40" style="fill: currentColor;color: white;">
                    <title>Facebook</title>
                    <defs>
                        <linearGradient x1="50%" x2="50%" y1="97.0782153%" y2="0%" id="jsc_c_2">
                            <stop offset="0%" stop-color="#0062E0"></stop>
                            <stop offset="100%" stop-color="#19AFFF"></stop>
                        </linearGradient>
                    </defs>
                    <path d="M15 35.8C6.5 34.3 0 26.9 0 18 0 8.1 8.1 0 18 0s18 8.1 18 18c0 8.9-6.5 16.3-15 17.8l-1-.8h-4l-1 .8z"></path>
                    <path class="p361ku9c" d="M25 23l.8-5H21v-3.5c0-1.4.5-2.5 2.7-2.5H26V7.4c-1.3-.2-2.7-.4-4-.4-4.1 0-7 2.5-7 7v4h-4.5v5H15v12.7c1 .2 2 .3 3 .3s2-.1 3-.3V23h4z" 
                          style="color: black;">
                    </path>
                </svg>
            </a>
            <a href="https://www.linkedin.com/in/guillermo-galvan-mendoza-39503a88/" target="_blank">
                <svg xmlns="http://www.w3.org/2000/svg" width="34" height="34" viewBox="0 0 34 34" class="global-nav__logo social-media" style="fill: currentColor;color: white;">
                    <title>LinkedIn</title>
                    <g>
                        <path d="M34,2.5v29A2.5,2.5,0,0,1,31.5,34H2.5A2.5,2.5,0,0,1,0,31.5V2.5A2.5,2.5,0,0,1,2.5,0h29A2.5,2.5,0,0,1,34,2.5ZM10,13H5V29h5Zm.45-5.5A2.88,2.88,0,0,0,7.59,4.6H7.5a2.9,2.9,0,0,0,0,5.8h0a2.88,2.88,0,0,0,2.95-2.81ZM29,19.28c0-4.81-3.06-6.68-6.1-6.68a5.7,5.7,0,0,0-5.06,2.58H17.7V13H13V29h5V20.49a3.32,3.32,0,0,1,3-3.58h.19c1.59,0,2.77,1,2.77,3.52V29h5Z"></path>
                    </g>
                </svg>
            </a>
        </div>
    </div>

    <div class="col-md-10 home-order-2">
        <div class="header-content header-image">
            <div class="header-content-box">
                <div class="firstline"><span class="color-text-red">Guillermo </span>Galván</div>
                <div class="secondline">
                    Desarrollador de software -
                    <span class="txt-rotate color-text-red" data-period="1200" data-rotate='[ " Front end.", " Back end.", " Desktop."]'>
                        <span class="wrap">full stack</span>
                    </span>
                    <span class="slash">|</span>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-1 home-order-3">
        <div class="contact">
            <a href="mailto:guillermo.galvan.mendoza@outlook.com"><img src="~/images/mail.png" alt="email-pic" class="contactpic"></a><!--Your email Id write in place of "#"-->            
        </div>
    </div>
</div>

src/GG.Portafolio.Site/Views/Home/Index.cshtml
@using GG.Portafolio.Shared.Blog
@model GG.Portafolio.Site.Models.DefaultViews

@{
    ViewData["Title"] = "Guillermo Galván";
}

<div id="home" class="display-none">
    @if (Model == DefaultViews.Home)
    {
        <partial name="Home.cshtml" />
    }
</div>

<div id="aboutme" class="display-none">
    @if (Model == DefaultViews.AboutMe)
    {
        <partial name="AboutMe.cshtml" />
    }
</div>

<div id="blog" class="display-none">
    @if (Model == DefaultViews.Blog)
    {
        <partial name="Blogs.cshtml" model="ViewBag.Blogs ?? new List<List<BlogResponse>>()" />
    }
</div>

<div id="portfolio" class="display-none">
    @if (Model == DefaultViews.Portfolio)
    {
        <partial name="Portfolio.cshtml" />
    }
</div>

<div class="display-none">
    <input type="hidden" value="@Url.Action("Home","Home")" id="linkHome" />
    <input type="hidden" value="@Url.Action("AboutMe","Home")" id="linkAboutMe" />
    <input type="hidden" value="@Url.Action("Portfolio","Home")" id="linkPortfolio" />
    <input type="hidden" value="@Url.Action("Blogs","Home")" id="linkBlog" />

    <input type="hidden" value="@((int)Model)" id="loadedView" />
</div>

@section Scripts{
    <environment include="Development">
        <script src="~/lib/bootstrap/js/bootstrap.bundle.js"></script>
    </environment>

    <environment exclude="Development">
        <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    </environment>

    <script src="~/js/home.js" asp-append-version="true"></script>
}

src/GG.Portafolio.Site/Views/Home/Portfolio.cshtml
<div class="row">
    <div class="col text-center header">
        <span class="color-text-red">Mí</span> Portafolio
    </div>
</div>

<div class="row">
    <div class="col text-center header-caption">
        <span class="header-caption">Algunos de mis <span class="color-text-red">trabajos y/o ejercicios.</span></span>
    </div>
</div>

<br />
<br />

<div class="row g-4 portfolio">

    <div class="col-md-5 offset-md-1 image">
        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Microsoft_Office_Word_%282019%E2%80%93present%29.svg/1200px-Microsoft_Office_Word_%282019%E2%80%93present%29.svg.png" alt="Template word">
    </div>

    <div class="col-md-5 align-self-center">
        <div class="description">
            <h2>Template Word</h2>
            <p>
                En este ejemplo se puede visualizas un ejemplo de llenado de un Word por medio de un
                témplate utilizando los datos que el usuario proporciona
            </p>
            <div class="button">
                <a class="btn btn-primary" asp-action="Index" asp-controller="TemplateWord">
                    <span class="index"> View Project<i class="gg-arrow-right"></i></span>
                </a>
            </div>
        </div>
    </div>
</div>

<br />
<br />

<div class="row g-4 portfolio">

    <div class="col-md-5 offset-md-1 image">
        <img src="https://img.freepik.com/vector-gratis/repartidor_1284-12633.jpg?size=338&ext=jpg" alt="Repartidores">
    </div>

    <div class="col-md-5 align-self-center">
        <div class="description">
            <h2>Manejo de repartidores</h2>
            <p>
                En este ejemplo se muestra un pequeño sistema de manejo de repartidores, en el se tiene una lista
                de 8 motociclistas en un horario de 9:00 am a 8:00 pm en el cual un usuario puede apartar un repartidor
                dentro del horario.
            </p>
            <div class="button">
                <a class="btn btn-primary" asp-action="Index" asp-controller="Dealer">
                    <span class="index"> View Project<i class="gg-arrow-right"></i></span>
                </a>
            </div>
        </div>
    </div>
</div>

<br />
<br />